version: "3"

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./storage:/var/www/storage
            - ./_docker/nginx/conf.d/prod/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - app
        container_name: crm_nginx
        networks:
            - lazurit
    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        command: certonly --webroot -w /var/www/certbot --force-renewal --email najmiddinov2006@gmail.com -d lazurit.uz --agree-tos
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        user: 1000:1000
        volumes:
            - ./:/var/www
            - ./storage:/var/www/storage
        depends_on:
            - db
        container_name: crm_app
        networks:
            - lazurit
    db:
        image: mysql:8.0
        restart: always
        volumes:
            - ./database/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: lazurit
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        networks:
            - lazurit
        container_name: crm_db

networks:
    lazurit: