version: "3"

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./storage:/var/www/storage
            - ./_docker/nginx/prod/conf.d/nginx.conf:/etc/nginx/conf.d
            - ./certbot/conf:/etc/nginx/ssl
            - ./certbot/www:/var/www/certbot
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - app
        container_name: crm_nginx
        networks:
            - lazurit
    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        command: certonly --webroot --webroot-path /var/www/certbot/ --email najmiddinov2006@gmail.com --agree-tos --no-eff-email     -d lazurit.uz  -d www.lazurit.uz --dry-run
        depends_on:
            - nginx
        networks:
            - lazurit
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        user: 1000:1000
        volumes:
            - ./:/var/www
            - ./storage:/var/www/storage
        depends_on:
            - db
        container_name: crm_app
        networks:
            - lazurit
    db:
        image: mysql:8.0
        restart: always
        volumes:
            - ./database/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: lazurit
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        networks:
            - lazurit
        container_name: crm_db

networks:
    lazurit:
        driver: bridge