version: "3"

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./storage:/var/www/storage
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
        ports:
            - "8876:80"
        depends_on:
            - app
        container_name: crm_nginx
        networks:
            - lazurit
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        user: 1000:1000
        volumes:
            - ./:/var/www
            - ./storage:/var/www/storage
        depends_on:
            - db
        container_name: crm_app
        networks:
            - lazurit
    composer:
        image: composer:latest
        volumes:
            - ./:/var/www
        working_dir: /var/www
        container_name: crm_composer
        networks:
            - lazurit

    npm:
        image: node:20.9-alpine
        volumes:
            - ./:/var/www
        working_dir: /var/www
        entrypoint: ['npm']
        container_name: crm_npm
        networks:
            - lazurit
    db:
        image: mysql:8.0
        restart: always
        volumes:
            - ./database/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: lazurit
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        networks:
            - lazurit
        container_name: crm_db

networks:
    lazurit: